"""empty message

Revision ID: 2deab9688cd7
Revises: 
Create Date: 2024-10-10 10:19:24.842499

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2deab9688cd7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("your_resource_model")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.VARCHAR(length=24),
            type_=sa.Numeric(precision=10, scale=2),
            postgresql_using="price::numeric(10, 2)",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Numeric(precision=10, scale=2),
            type_=sa.VARCHAR(length=24),
            existing_nullable=True,
        )

    op.create_table(
        "your_resource_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=63), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="your_resource_model_pkey"),
    )
    # ### end Alembic commands ###
